name: hysys

services:
  backend:
    container_name: hysys-backend
    image: dataelement/mep-backend:v2.4.0-beta1
    ports:
      - "7861:7861"
    environment:
      TZ: Asia/Shanghai
      MEP_PRO: 'true'
      MEP_MILVUS_CONNECTION_ARGS: '{"host":"milvus","port":"19530","user":"","password":"","secure":false}'
      MEP_MILVUS_IS_PARTITION: 'true'
      MEP_MILVUS_PARTITION_SUFFIX: '2'
      MEP_ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      MEP_ELASTICSEARCH_SSL_VERIFY: '{}'
      MEP_MINIO_SCHEMA: 'false'
      MEP_MINIO_CERT_CHECK: 'false'
      MEP_MINIO_ENDPOINT: 'minio:9000'
      MEP_MINIO_SHAREPOINT: 'minio:9000'
      MEP_MINIO_ACCESS_KEY: 'minioadmin'
      MEP_MINIO_SECRET_KEY: 'minioadmin'
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config/config.yaml:/app/mep/config.yaml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/entrypoint.sh:/app/entrypoint.sh
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/hysys:/app/data
    deploy:
      resources:
        limits:
          memory: 1536m
    security_opt:
      - seccomp:unconfined
    command: sh entrypoint.sh api
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7861/health"]
      start_period: 90s
      interval: 90s
      timeout: 30s
      retries: 3
    networks:
      - shared-infra

  backend_worker:
    container_name: hysys-backend-worker
    image: dataelement/mep-backend:v2.4.0-beta1
    environment:
      TZ: Asia/Shanghai
      MEP_PRO: 'true'
      MEP_MILVUS_CONNECTION_ARGS: '{"host":"milvus","port":"19530","user":"","password":"","secure":false}'
      MEP_MILVUS_IS_PARTITION: 'true'
      MEP_MILVUS_PARTITION_SUFFIX: '2'
      MEP_ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      MEP_ELASTICSEARCH_SSL_VERIFY: '{}'
      MEP_MINIO_SCHEMA: 'false'
      MEP_MINIO_CERT_CHECK: 'false'
      MEP_MINIO_ENDPOINT: 'minio:9000'
      MEP_MINIO_SHAREPOINT: 'minio:9000'
      MEP_MINIO_ACCESS_KEY: 'minioadmin'
      MEP_MINIO_SECRET_KEY: 'minioadmin'
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config/config.yaml:/app/mep/config.yaml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/entrypoint.sh:/app/entrypoint.sh
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/hysys:/app/data
    deploy:
      resources:
        limits:
          memory: 1g
    security_opt:
      - seccomp:unconfined
    command: sh entrypoint.sh worker
    restart: on-failure
    networks:
      - shared-infra

  frontend:
    container_name: hysys-frontend
    image: dataelement/mep-frontend:v2.4.0-beta1
    ports:
      - "3002:3002"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_VOLUME_DIRECTORY:-.}/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/hysys/reports:/usr/share/nginx/html/reports:ro
    deploy:
      resources:
        limits:
          memory: 128m
    restart: on-failure
    depends_on:
      - backend
    networks:
      - shared-infra

networks:
  shared-infra:
    external: true
    name: docker_default
